apiVersion: v1
kind: Service
metadata:
  name: redis-client-service
  labels:
    app: rest
    role: redis-client
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: rest
    role: redis-client
    tier: backend