apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-client-contr
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: rest
    role: redis-client
    tier: backend
spec:
  replicas: 1
  # Pod Template
  template:
    metadata:
      labels:
        app: rest
        role: redis-client
        tier: backend
    spec:
      containers:
      - name: rest-redis
        image: djob195/client-redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "8081"
        - name: REST_API
          value: "http://rest-service:8080/"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: "redis-master-service" 
        ports:
        - containerPort: 8081