apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-client-contr
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: rest
    role: redis-client
    tier: backend
spec:
  replicas: 1
  # Pod Template
  template:
    metadata:
      labels:
        app: rest
        role: redis-client
        tier: backend
    spec:
      containers:
      - name: rest-redis
        image: 
        args: ["8080"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: 8080
        - name: REST_API
          value: http://rest-service
        - name: REDIS_PORT
          value: redis-master
        - name: REDIS_HOST
          value: 6379  
        ports:
        - containerPort: 8080