apiVersion: v1
kind: Service
metadata:
  name: redis-client-service
  labels:
    app: rest
    role: redis-client
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rest
    role: redis-client
    tier: backend