apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  labels:
    app: rest
    role: master
    tier: backend  
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: rest
    role: master
    tier: backend  