apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    app: rest
    role: rest-client
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: rest
    role: rest-client
    tier: backend