apiVersion: v1
kind: ReplicationController
metadata:
  name: rest-contr
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: rest
    tier: backend
spec:
  replicas: 1
  # Pod Template
  template:
    metadata:
      labels:
        app: rest
        tier: backend
    spec:
      containers:
      - name: restweb
        # Uncomment this line to use the public docker hub image
        image: djob195/rest-web2
        resources:
          # The resources specification for each Pod, more details here:
          # http://kubernetes.io/v1.1/docs/design/resources.html#resource-specifications
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "8080" 
        - name: NODE_ENV
          value: "prod"
        - name: URLDB
          value: "mongodb://admin:123456A@ds255253.mlab.com:55253/web2"
        ports:
          # More details on the container ports here,
          # http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html#_v1_containerport
          # The port exposed by the container
        - containerPort: 8080