apiVersion: v1
kind: ReplicationController
metadata:
  name: rest-contr
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: rest
    role: api-db
    tier: backend
spec:
  replicas: 1
  # Pod Template
  template:
    metadata:
      labels:
        app: web
        role: api-db
        tier: backend
    spec:
      containers:
      - name: rest-web
        image: 
        args: ["3000"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: 3000
        - name: NODE_ENV
          value: prod
        - name: URLDB
          value: mongodb://admin:123456A@ds255253.mlab.com:55253/web2                                  
        ports:
        - containerPort: 3000