apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    app: rest
    role: api-db
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: rest
    role: api-db
    tier: backend