apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-contr
  labels:
    app: frontend-web
    role: web
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-web
        role: web
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: djob195/web
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80